[package]
name = "dataset_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.0"
flate2 = { version = "1.1.9", default-features = false, features = ["zlib"] }
parry3d = "0.30.0"
polysim = { git = "https://github.com/SpideyZac/polysim.git" }
polytrack-codes = { git = "https://codeberg.org/GameBuilder202/polycodes.git", branch = "trait-rewrite" }
polyworld = { git = "https://github.com/SpideyZac/polyworld.git" }
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
wasmtime = "47.0.3"
